Output stage to LDM replication started,
Synchronization mode: all datasets
=============== Mapping ===============

---- Table opportunity -> Dataset dataset.opportunity ----
a__title -> label.opportunity.title
f__totalprice -> fact.opportunity.totalprice
f__price -> fact.opportunity.price
cp__nameErrorMapping -> NameErrorMapping [NEW label]


---- Table person -> Dataset dataset.person ----
l__person__firstname -> label.person.person.firstname
l__person__lastname -> label.person.person.lastname
l__person__personid -> label.person.person.personid
f__age -> fact.person.age
a__personErrorMapping -> PersonErrorMapping [NEW label]


=============== End of Mapping ===============

=============== Validation Problems ===============
---- Dataset dataset.opportunity ----
Expected output stage table column 'opportunity.cp__name' for LDM field 'label.opportunity.name' does not exist.


---- Dataset dataset.person ----
Expected output stage table column 'person.a__person' for LDM field 'label.person.person' does not exist.


=============== End of Validation Problems ===============

Dataset 'dataset.opportunity' has mapping with errors: ValidationProblem{message='Expected output stage table column '%s' for LDM field '%s' does not exist.', messageParameters=[opportunity.cp__name, label.opportunity.name], type=UNMAPPED_DATASET_FIELD, severity=ERROR, datasetId=dataset.opportunity}.
Dataset 'dataset.person' has mapping with errors: ValidationProblem{message='Expected output stage table column '%s' for LDM field '%s' does not exist.', messageParameters=[person.a__person, label.person.person], type=UNMAPPED_DATASET_FIELD, severity=ERROR, datasetId=dataset.person}.
Data loader failed, reason:
Following datasets have invalid mapping: dataset.opportunity, dataset.person
